-- AUTO-GENERATED. Run after 01_schema.sql.
begin;
truncate feature_importances, model_scores, results, predictions, drivers, races restart identity cascade;

insert into races (chase_round, name, track, race_date, track_type, track_length_mi, status, winner, blend_note) values
  (1, 'Cook Out Southern 500', 'Darlington Raceway', '2026-09-07', 'Intermediate', 1.366, 'completed', 'Christopher Bell', '60% intermediate season form / 40% Darlington Chase history'),
  (2, 'Enjoy Illinois 300', 'World Wide Technology Raceway', '2026-09-13', 'Intermediate', 1.25, 'upcoming', null, null),
  (3, 'Bass Pro Shops Night Race', 'Bristol Motor Speedway', '2026-09-19', 'Short Track', 0.533, 'upcoming', null, null),
  (4, 'Hollywood Casino 400', 'Kansas Speedway', '2026-09-27', 'Intermediate', 1.5, 'upcoming', null, null),
  (5, 'South Point 400', 'Las Vegas Motor Speedway', '2026-10-04', 'Intermediate', 1.5, 'upcoming', null, null),
  (6, 'Bank of America 400', 'Charlotte Motor Speedway', '2026-10-11', 'Intermediate', 1.5, 'upcoming', null, null),
  (7, 'Freeway Insurance 500', 'Phoenix Raceway', '2026-10-18', 'Intermediate', 1.0, 'upcoming', null, null),
  (8, 'YellaWood 500', 'Talladega Superspeedway', '2026-10-25', 'Superspeedway', 2.66, 'upcoming', null, null),
  (9, 'Xfinity 500', 'Martinsville Speedway', '2026-11-01', 'Short Track', 0.526, 'upcoming', null, null),
  (10, 'NASCAR Cup Series Championship Race', 'Homestead-Miami Speedway', '2026-11-08', 'Intermediate', 1.5, 'upcoming', null, null);

insert into drivers (name, car_number, is_chase_driver) values
  ('AJ Allmendinger', 16, false),
  ('Alex Bowman', 48, false),
  ('Austin Cindric', 2, true),
  ('Austin Dillon', 3, false),
  ('Austin Hill', 33, false),
  ('Brad Keselowski', 6, false),
  ('Bubba Wallace', 23, true),
  ('Carson Hocevar', 77, true),
  ('Chad Finchum', 66, false),
  ('Chase Briscoe', 19, true),
  ('Chase Elliott', 9, true),
  ('Chris Buescher', 17, true),
  ('Christopher Bell', 20, true),
  ('Cody Ware', 51, false),
  ('Cole Custer', 41, false),
  ('Connor Zilisch', 88, false),
  ('Corey Heim', 67, false),
  ('Daniel Suarez', 7, true),
  ('Denny Hamlin', 11, true),
  ('Erik Jones', 43, false),
  ('Joey Logano', 22, true),
  ('John Hunter Nemechek', 42, false),
  ('Josh Berry', 21, false),
  ('Kyle Larson', 5, true),
  ('Michael McDowell', 71, false),
  ('Noah Gragson', 4, false),
  ('Ricky Stenhouse Jr.', 47, false),
  ('Riley Herbst', 35, false),
  ('Ross Chastain', 1, false),
  ('Ryan Blaney', 12, true),
  ('Ryan Preece', 60, true),
  ('Shane Van Gisbergen', 97, false),
  ('Todd Gilliland', 34, false),
  ('Ty Dillon', 10, false),
  ('Ty Gibbs', 54, true),
  ('Tyler Reddick', 45, true),
  ('William Byron', 24, true),
  ('Zane Smith', 38, false);

insert into predictions (race_id, driver_id, model_type, projected_finish, data_source) values
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Tyler Reddick'), 'basic', 8.9, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'William Byron'), 'basic', 10.2, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Denny Hamlin'), 'basic', 10.3, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Chase Briscoe'), 'basic', 12.7, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Chris Buescher'), 'basic', 12.9, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Daniel Suarez'), 'basic', 13.8, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Carson Hocevar'), 'basic', 13.9, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Bubba Wallace'), 'basic', 14.0, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ty Gibbs'), 'basic', 14.1, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Christopher Bell'), 'basic', 14.2, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ryan Blaney'), 'basic', 14.2, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Chase Elliott'), 'basic', 14.7, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Brad Keselowski'), 'basic', 14.9, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Kyle Larson'), 'basic', 15.1, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Erik Jones'), 'basic', 18.0, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Joey Logano'), 'basic', 18.2, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Austin Cindric'), 'basic', 18.2, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Alex Bowman'), 'basic', 18.6, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Shane Van Gisbergen'), 'basic', 19.5, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Zane Smith'), 'basic', 19.7, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ricky Stenhouse Jr.'), 'basic', 20.2, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ross Chastain'), 'basic', 20.2, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ryan Preece'), 'basic', 20.7, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Austin Dillon'), 'basic', 21.4, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Michael McDowell'), 'basic', 22.2, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Todd Gilliland'), 'basic', 22.2, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Corey Heim'), 'basic', 22.4, 'Track-Type Form Only (no Darlington history)'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Riley Herbst'), 'basic', 24.2, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'John Hunter Nemechek'), 'basic', 24.4, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Connor Zilisch'), 'basic', 24.7, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'AJ Allmendinger'), 'basic', 24.9, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Cole Custer'), 'basic', 25.7, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Josh Berry'), 'basic', 25.8, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Austin Hill'), 'basic', 25.8, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ty Dillon'), 'basic', 26.0, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Noah Gragson'), 'basic', 27.3, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Chad Finchum'), 'basic', 30.0, 'Track-Type Form Only (no Darlington history)'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Cody Ware'), 'basic', 30.1, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Tyler Reddick'), 'advanced', 8.8, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Denny Hamlin'), 'advanced', 8.9, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Chase Elliott'), 'advanced', 10.3, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'William Byron'), 'advanced', 11.6, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Brad Keselowski'), 'advanced', 11.8, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Chase Briscoe'), 'advanced', 13.0, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ty Gibbs'), 'advanced', 13.6, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Erik Jones'), 'advanced', 13.9, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ryan Blaney'), 'advanced', 14.4, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Chris Buescher'), 'advanced', 14.9, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Christopher Bell'), 'advanced', 15.1, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Daniel Suarez'), 'advanced', 16.6, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Carson Hocevar'), 'advanced', 17.2, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Bubba Wallace'), 'advanced', 17.2, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ryan Preece'), 'advanced', 17.9, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Austin Cindric'), 'advanced', 18.0, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Kyle Larson'), 'advanced', 18.7, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ross Chastain'), 'advanced', 19.2, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Joey Logano'), 'advanced', 19.2, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Alex Bowman'), 'advanced', 19.8, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Corey Heim'), 'advanced', 20.5, 'Track-Type Form Only (no Darlington history)'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Zane Smith'), 'advanced', 21.2, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Austin Dillon'), 'advanced', 21.9, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Shane Van Gisbergen'), 'advanced', 22.0, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ricky Stenhouse Jr.'), 'advanced', 22.0, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'AJ Allmendinger'), 'advanced', 23.5, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Noah Gragson'), 'advanced', 23.5, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Connor Zilisch'), 'advanced', 23.6, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Todd Gilliland'), 'advanced', 23.7, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Cole Custer'), 'advanced', 23.9, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'John Hunter Nemechek'), 'advanced', 24.0, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Michael McDowell'), 'advanced', 24.1, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ty Dillon'), 'advanced', 24.2, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Riley Herbst'), 'advanced', 24.6, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Josh Berry'), 'advanced', 25.7, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Austin Hill'), 'advanced', 27.4, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Chad Finchum'), 'advanced', 29.7, 'Track-Type Form Only (no Darlington history)'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Cody Ware'), 'advanced', 30.3, 'Darlington Chase History + Track-Type Form');

insert into results (race_id, driver_id, start_pos, finish_pos, status, avg_running_position, fastest_laps, laps_led, pct_led, quality_passes, pct_top15) values
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Christopher Bell'), 11, 1, 'Running', 4.98, 26, 46, 12.53, 68, 97.55),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ty Gibbs'), 28, 2, 'Running', 11.2, 14, 0, 0.0, 49, 85.01),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Tyler Reddick'), 1, 3, 'Running', 3.44, 27, 74, 20.16, 49, 99.18),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ryan Blaney'), 24, 4, 'Running', 7.99, 13, 1, 0.27, 64, 89.65),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Kyle Larson'), 25, 5, 'Running', 10.01, 59, 99, 26.98, 42, 75.48),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Chase Briscoe'), 7, 6, 'Running', 6.63, 15, 30, 8.17, 65, 89.92),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Josh Berry'), 14, 7, 'Running', 9.55, 13, 0, 0.0, 67, 90.19),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Bubba Wallace'), 17, 8, 'Running', 5.73, 13, 38, 10.35, 55, 99.18),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Joey Logano'), 13, 9, 'Running', 12.44, 2, 0, 0.0, 49, 85.29),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ryan Preece'), 3, 10, 'Running', 14.8, 2, 0, 0.0, 16, 53.68),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Carson Hocevar'), 34, 11, 'Running', 15.62, 2, 2, 0.54, 45, 57.22),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Alex Bowman'), 10, 12, 'Running', 14.49, 0, 0, 0.0, 31, 59.13),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Austin Cindric'), 6, 13, 'Running', 9.07, 7, 0, 0.0, 50, 96.46),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Chase Elliott'), 18, 14, 'Running', 12.7, 7, 1, 0.27, 67, 86.38),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Erik Jones'), 36, 15, 'Running', 17.46, 0, 0, 0.0, 39, 36.78),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Todd Gilliland'), 21, 16, 'Running', 20.27, 2, 5, 1.36, 26, 19.89),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Michael McDowell'), 5, 17, 'Running', 13.59, 4, 0, 0.0, 43, 63.49),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Denny Hamlin'), 4, 18, 'Running', 8.45, 39, 68, 18.53, 40, 62.94),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Corey Heim'), 22, 19, 'Running', 28.46, 5, 0, 0.0, 5, 1.36),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Chris Buescher'), 35, 20, 'Running', 24.36, 1, 0, 0.0, 5, 7.08),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Daniel Suarez'), 2, 21, 'Running', 20.51, 3, 2, 0.54, 25, 14.17),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'AJ Allmendinger'), 30, 22, 'Running', 23.96, 7, 0, 0.0, 4, 0.54),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Brad Keselowski'), 12, 23, 'Running', 20.58, 4, 0, 0.0, 10, 24.25),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'John Hunter Nemechek'), 19, 24, 'Running', 24.51, 0, 0, 0.0, 12, 4.09),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Zane Smith'), 33, 25, 'Running', 22.29, 0, 0, 0.0, 12, 3.54),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Shane Van Gisbergen'), 26, 26, 'Running', 33.12, 10, 1, 0.27, 10, 1.64),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ross Chastain'), 23, 27, 'Running', 25.33, 5, 0, 0.0, 10, 1.37),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Austin Hill'), 32, 28, 'Running', 24.97, 0, 0, 0.0, 14, 2.73),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Austin Dillon'), 9, 29, 'Running', 28.08, 0, 0, 0.0, 3, 3.83),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Riley Herbst'), 15, 30, 'Running', 21.81, 1, 0, 0.0, 8, 1.91),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ty Dillon'), 27, 31, 'Running', 32.47, 0, 0, 0.0, 0, 0.0),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Noah Gragson'), 29, 32, 'Running', 31.59, 0, 0, 0.0, 5, 0.55),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Cole Custer'), 16, 33, 'Running', 30.9, 30, 0, 0.0, 3, 0.27),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Connor Zilisch'), 31, 34, 'Running', 33.5, 0, 0, 0.0, 0, 0.27),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ricky Stenhouse Jr.'), 8, 35, 'Running', 33.28, 0, 0, 0.0, 6, 6.61),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Cody Ware'), 37, 36, 'Running', 36.13, 0, 0, 0.0, 2, 0.55),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'William Byron'), 20, 37, 'Engine', 9.7, 5, 0, 0.0, 47, 89.66),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Chad Finchum'), 38, 38, 'Suspension', 37.93, 0, 0, 0.0, 0, 0.0);

insert into model_scores (race_id, model_type, cv_mae, cv_r2, mae, rmse, r2, top5_hits, top10_hits, predicted_winner, predicted_winner_actual_finish) values
  ((select id from races where chase_round = 1), 'basic', 2.488, 0.783, 7.51, 8.93, 0.336, 1, 5, 'Tyler Reddick', 3),
  ((select id from races where chase_round = 1), 'advanced', 2.38, 0.8, 7.79, 9.20, 0.296, 1, 4, 'Tyler Reddick', 3);

insert into feature_importances (race_id, model_type, feature, importance) values
  ((select id from races where chase_round = 1), 'basic', 'T10%', 0.5755),
  ((select id from races where chase_round = 1), 'basic', 'Succ%', 0.2241),
  ((select id from races where chase_round = 1), 'basic', 'ASP', 0.1772),
  ((select id from races where chase_round = 1), 'basic', 'W%', 0.0174),
  ((select id from races where chase_round = 1), 'basic', 'Fin%', 0.0059),
  ((select id from races where chase_round = 1), 'advanced', 'Avg. PFAE', 0.4559),
  ((select id from races where chase_round = 1), 'advanced', 'ARP', 0.3596),
  ((select id from races where chase_round = 1), 'advanced', 'cPOMS', 0.0829),
  ((select id from races where chase_round = 1), 'advanced', 'SS', 0.0617),
  ((select id from races where chase_round = 1), 'advanced', 'PGAE', 0.0399);

commit;
