-- Standalone: Gateway (race 2) predictions + feature importances.
-- Safe to re-run; replaces any existing Gateway rows.
begin;
update races set blend_note = '70% flat-mile season form / 30% Gateway Chase history' where chase_round = 2;

delete from predictions where race_id = (select id from races where chase_round = 2);
delete from feature_importances where race_id = (select id from races where chase_round = 2);

insert into predictions (race_id, driver_id, model_type, projected_finish, data_source) values
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Denny Hamlin'), 'basic', 7.7, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Ryan Blaney'), 'basic', 7.8, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Christopher Bell'), 'basic', 8.6, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Ty Gibbs'), 'basic', 9.3, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Kyle Larson'), 'basic', 10.2, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Joey Logano'), 'basic', 10.8, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'William Byron'), 'basic', 11.6, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Tyler Reddick'), 'basic', 14.6, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Chase Elliott'), 'basic', 14.6, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Chase Briscoe'), 'basic', 15.4, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Michael McDowell'), 'basic', 18.0, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Austin Dillon'), 'basic', 18.5, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Austin Cindric'), 'basic', 18.7, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Chris Buescher'), 'basic', 19.0, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Zane Smith'), 'basic', 19.2, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Ryan Preece'), 'basic', 19.3, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Bubba Wallace'), 'basic', 19.3, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Josh Berry'), 'basic', 19.4, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Daniel Suarez'), 'basic', 19.8, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Brad Keselowski'), 'basic', 22.5, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Ricky Stenhouse Jr.'), 'basic', 22.7, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Ross Chastain'), 'basic', 22.8, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Alex Bowman'), 'basic', 23.1, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Todd Gilliland'), 'basic', 23.1, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'AJ Allmendinger'), 'basic', 23.1, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Shane Van Gisbergen'), 'basic', 23.1, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Carson Hocevar'), 'basic', 23.2, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Erik Jones'), 'basic', 23.3, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Noah Gragson'), 'basic', 23.4, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Riley Herbst'), 'basic', 23.4, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Austin Hill'), 'basic', 24.0, 'Flat-Mile Form Only (no Gateway history)'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'John Hunter Nemechek'), 'basic', 24.8, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Connor Zilisch'), 'basic', 25.5, 'Flat-Mile Form Only (no Gateway history)'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Cole Custer'), 'basic', 26.0, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Ty Dillon'), 'basic', 28.1, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Cody Ware'), 'basic', 28.6, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Christopher Bell'), 'advanced', 7.2, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Ryan Blaney'), 'advanced', 7.7, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Denny Hamlin'), 'advanced', 8.0, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Ty Gibbs'), 'advanced', 12.2, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Joey Logano'), 'advanced', 13.0, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Chase Briscoe'), 'advanced', 13.6, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Kyle Larson'), 'advanced', 14.4, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Bubba Wallace'), 'advanced', 15.0, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Chase Elliott'), 'advanced', 15.7, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Tyler Reddick'), 'advanced', 15.9, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Chris Buescher'), 'advanced', 17.0, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'William Byron'), 'advanced', 17.3, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Ryan Preece'), 'advanced', 17.3, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Austin Dillon'), 'advanced', 17.6, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Austin Cindric'), 'advanced', 18.6, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Michael McDowell'), 'advanced', 19.8, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Noah Gragson'), 'advanced', 20.2, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Zane Smith'), 'advanced', 20.2, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'AJ Allmendinger'), 'advanced', 20.4, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Daniel Suarez'), 'advanced', 20.4, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Shane Van Gisbergen'), 'advanced', 20.4, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Todd Gilliland'), 'advanced', 20.8, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'John Hunter Nemechek'), 'advanced', 21.0, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Josh Berry'), 'advanced', 21.8, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Brad Keselowski'), 'advanced', 22.4, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Ty Dillon'), 'advanced', 22.5, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Erik Jones'), 'advanced', 22.9, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Riley Herbst'), 'advanced', 23.0, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Alex Bowman'), 'advanced', 23.0, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Carson Hocevar'), 'advanced', 23.0, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Ricky Stenhouse Jr.'), 'advanced', 23.5, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Ross Chastain'), 'advanced', 24.2, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Austin Hill'), 'advanced', 24.8, 'Flat-Mile Form Only (no Gateway history)'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Connor Zilisch'), 'advanced', 25.3, 'Flat-Mile Form Only (no Gateway history)'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Cole Custer'), 'advanced', 25.4, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Cody Ware'), 'advanced', 29.1, 'Gateway Chase History + Flat-Mile Form');

insert into feature_importances (race_id, model_type, feature, importance) values
  ((select id from races where chase_round = 2), 'basic', 'Succ%', 0.4313),
  ((select id from races where chase_round = 2), 'basic', 'T10%', 0.3939),
  ((select id from races where chase_round = 2), 'basic', 'ASP', 0.1358),
  ((select id from races where chase_round = 2), 'basic', 'W%', 0.0196),
  ((select id from races where chase_round = 2), 'basic', 'Fin%', 0.0193),
  ((select id from races where chase_round = 2), 'advanced', 'Avg. PFAE', 0.6052),
  ((select id from races where chase_round = 2), 'advanced', 'ARP', 0.1357),
  ((select id from races where chase_round = 2), 'advanced', 'SS', 0.1158),
  ((select id from races where chase_round = 2), 'advanced', 'PGAE', 0.0953),
  ((select id from races where chase_round = 2), 'advanced', 'cPOMS', 0.048);
commit;
