-- ARP -> wARP advanced-model swap for Darlington (r1) + Gateway (r2).
-- Safe to re-run.
begin;

delete from predictions where race_id = (select id from races where chase_round = 1) and model_type = 'advanced';
delete from feature_importances where race_id = (select id from races where chase_round = 1) and model_type = 'advanced';
delete from predictions where race_id = (select id from races where chase_round = 2) and model_type = 'advanced';
delete from feature_importances where race_id = (select id from races where chase_round = 2) and model_type = 'advanced';

insert into predictions (race_id, driver_id, model_type, projected_finish, data_source) values
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Tyler Reddick'), 'advanced', 8.9, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Denny Hamlin'), 'advanced', 8.9, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Chase Elliott'), 'advanced', 10.3, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'William Byron'), 'advanced', 11.7, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Brad Keselowski'), 'advanced', 11.9, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Chase Briscoe'), 'advanced', 13.0, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Erik Jones'), 'advanced', 13.6, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ty Gibbs'), 'advanced', 13.6, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ryan Blaney'), 'advanced', 14.3, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Chris Buescher'), 'advanced', 15.0, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Christopher Bell'), 'advanced', 15.2, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Daniel Suarez'), 'advanced', 16.3, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Bubba Wallace'), 'advanced', 16.9, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Carson Hocevar'), 'advanced', 17.0, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ryan Preece'), 'advanced', 17.8, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Austin Cindric'), 'advanced', 18.0, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Kyle Larson'), 'advanced', 18.1, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ross Chastain'), 'advanced', 18.7, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Joey Logano'), 'advanced', 18.7, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Alex Bowman'), 'advanced', 20.0, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Corey Heim'), 'advanced', 20.6, 'Track-Type Form Only (no Darlington history)'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Zane Smith'), 'advanced', 21.1, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Shane Van Gisbergen'), 'advanced', 22.0, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Austin Dillon'), 'advanced', 22.3, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ricky Stenhouse Jr.'), 'advanced', 22.3, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'AJ Allmendinger'), 'advanced', 23.6, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Connor Zilisch'), 'advanced', 23.7, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Noah Gragson'), 'advanced', 23.7, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Cole Custer'), 'advanced', 23.8, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'John Hunter Nemechek'), 'advanced', 23.9, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Michael McDowell'), 'advanced', 24.0, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Todd Gilliland'), 'advanced', 24.2, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Ty Dillon'), 'advanced', 24.6, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Riley Herbst'), 'advanced', 24.6, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Josh Berry'), 'advanced', 25.4, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Austin Hill'), 'advanced', 27.4, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Chad Finchum'), 'advanced', 29.7, 'Track-Type Form Only (no Darlington history)'),
  ((select id from races where chase_round = 1), (select id from drivers where name = 'Cody Ware'), 'advanced', 30.3, 'Darlington Chase History + Track-Type Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Christopher Bell'), 'advanced', 7.2, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Ryan Blaney'), 'advanced', 7.6, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Denny Hamlin'), 'advanced', 8.1, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Ty Gibbs'), 'advanced', 11.7, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Joey Logano'), 'advanced', 13.4, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Chase Briscoe'), 'advanced', 13.9, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Kyle Larson'), 'advanced', 14.2, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Bubba Wallace'), 'advanced', 15.0, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Tyler Reddick'), 'advanced', 15.6, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Chase Elliott'), 'advanced', 15.6, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Chris Buescher'), 'advanced', 16.9, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'William Byron'), 'advanced', 17.2, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Ryan Preece'), 'advanced', 17.3, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Austin Dillon'), 'advanced', 17.4, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Austin Cindric'), 'advanced', 18.6, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Michael McDowell'), 'advanced', 19.7, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Noah Gragson'), 'advanced', 20.0, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Shane Van Gisbergen'), 'advanced', 20.4, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Zane Smith'), 'advanced', 20.4, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Daniel Suarez'), 'advanced', 20.4, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'AJ Allmendinger'), 'advanced', 20.6, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Todd Gilliland'), 'advanced', 20.7, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'John Hunter Nemechek'), 'advanced', 21.0, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Josh Berry'), 'advanced', 21.6, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Brad Keselowski'), 'advanced', 22.3, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Alex Bowman'), 'advanced', 22.7, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Erik Jones'), 'advanced', 22.8, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Carson Hocevar'), 'advanced', 23.0, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Riley Herbst'), 'advanced', 23.0, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Ricky Stenhouse Jr.'), 'advanced', 23.5, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Ty Dillon'), 'advanced', 24.3, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Ross Chastain'), 'advanced', 24.5, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Austin Hill'), 'advanced', 25.5, 'Flat-Mile Form Only (no Gateway history)'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Connor Zilisch'), 'advanced', 25.6, 'Flat-Mile Form Only (no Gateway history)'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Cole Custer'), 'advanced', 27.1, 'Gateway Chase History + Flat-Mile Form'),
  ((select id from races where chase_round = 2), (select id from drivers where name = 'Cody Ware'), 'advanced', 28.6, 'Gateway Chase History + Flat-Mile Form');

insert into feature_importances (race_id, model_type, feature, importance) values
  ((select id from races where chase_round = 1), 'advanced', 'wARP', 0.4895),
  ((select id from races where chase_round = 1), 'advanced', 'Avg. PFAE', 0.3689),
  ((select id from races where chase_round = 1), 'advanced', 'SS', 0.0637),
  ((select id from races where chase_round = 1), 'advanced', 'cPOMS', 0.0396),
  ((select id from races where chase_round = 1), 'advanced', 'PGAE', 0.0384),
  ((select id from races where chase_round = 2), 'advanced', 'Avg. PFAE', 0.6146),
  ((select id from races where chase_round = 2), 'advanced', 'SS', 0.1262),
  ((select id from races where chase_round = 2), 'advanced', 'PGAE', 0.1035),
  ((select id from races where chase_round = 2), 'advanced', 'wARP', 0.1018),
  ((select id from races where chase_round = 2), 'advanced', 'cPOMS', 0.0539);

update model_scores set cv_mae = 2.301, cv_r2 = 0.807, mae = 7.75, rmse = 9.12, r2 = 0.308, top5_hits = 1, top10_hits = 4, predicted_winner = 'Tyler Reddick', predicted_winner_actual_finish = 3 where race_id = (select id from races where chase_round = 1) and model_type = 'advanced';
commit;
