-- Standalone: Bristol (race 3) predictions + feature importances.
-- Safe to re-run; replaces any existing Bristol rows.
begin;
update races set blend_note = '60% short-track season form / 40% Bristol Chase history' where chase_round = 3;

-- Josh Bilicki is in the Bristol entry list but wasn't in an earlier field
insert into drivers (name, car_number, is_chase_driver) values ('Josh Bilicki', 66, false)
  on conflict (name) do nothing;

delete from predictions where race_id = (select id from races where chase_round = 3);
delete from feature_importances where race_id = (select id from races where chase_round = 3);

insert into predictions (race_id, driver_id, model_type, projected_finish, data_source) values
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Ty Gibbs'), 'basic', 7.8, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Denny Hamlin'), 'basic', 8.0, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Ryan Blaney'), 'basic', 9.2, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Christopher Bell'), 'basic', 9.3, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Kyle Larson'), 'basic', 9.9, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Ryan Preece'), 'basic', 13.0, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Chase Briscoe'), 'basic', 13.9, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'William Byron'), 'basic', 14.2, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Tyler Reddick'), 'basic', 14.3, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Joey Logano'), 'basic', 14.5, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Brad Keselowski'), 'basic', 14.8, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Bubba Wallace'), 'basic', 15.2, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Chase Elliott'), 'basic', 15.7, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Josh Berry'), 'basic', 16.1, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Ross Chastain'), 'basic', 17.5, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Alex Bowman'), 'basic', 17.6, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Carson Hocevar'), 'basic', 17.7, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Chris Buescher'), 'basic', 18.1, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Michael McDowell'), 'basic', 18.4, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Austin Dillon'), 'basic', 19.8, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Daniel Suarez'), 'basic', 19.8, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Todd Gilliland'), 'basic', 20.2, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Austin Cindric'), 'basic', 21.0, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Zane Smith'), 'basic', 21.5, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'AJ Allmendinger'), 'basic', 21.6, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Riley Herbst'), 'basic', 23.6, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'John Hunter Nemechek'), 'basic', 24.1, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Erik Jones'), 'basic', 24.1, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Shane Van Gisbergen'), 'basic', 24.2, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Noah Gragson'), 'basic', 24.4, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Ricky Stenhouse Jr.'), 'basic', 25.0, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Connor Zilisch'), 'basic', 25.6, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Cole Custer'), 'basic', 26.0, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Ty Dillon'), 'basic', 29.6, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Austin Hill'), 'basic', 30.5, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Cody Ware'), 'basic', 30.9, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Josh Bilicki'), 'basic', 31.6, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Denny Hamlin'), 'advanced', 7.9, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Ty Gibbs'), 'advanced', 8.0, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Kyle Larson'), 'advanced', 8.4, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Christopher Bell'), 'advanced', 8.6, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Ryan Blaney'), 'advanced', 10.1, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Chase Briscoe'), 'advanced', 12.4, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Ryan Preece'), 'advanced', 12.8, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Brad Keselowski'), 'advanced', 14.4, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Joey Logano'), 'advanced', 14.9, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Chase Elliott'), 'advanced', 15.6, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Chris Buescher'), 'advanced', 15.7, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'William Byron'), 'advanced', 16.5, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Bubba Wallace'), 'advanced', 16.5, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Tyler Reddick'), 'advanced', 17.2, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Ross Chastain'), 'advanced', 18.3, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Carson Hocevar'), 'advanced', 18.6, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Josh Berry'), 'advanced', 18.6, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Austin Cindric'), 'advanced', 19.0, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Alex Bowman'), 'advanced', 19.6, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Todd Gilliland'), 'advanced', 20.2, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Daniel Suarez'), 'advanced', 20.7, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Michael McDowell'), 'advanced', 20.8, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Austin Dillon'), 'advanced', 20.9, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Noah Gragson'), 'advanced', 22.4, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'AJ Allmendinger'), 'advanced', 22.9, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Zane Smith'), 'advanced', 23.2, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Riley Herbst'), 'advanced', 23.3, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Erik Jones'), 'advanced', 23.8, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Ricky Stenhouse Jr.'), 'advanced', 24.1, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'John Hunter Nemechek'), 'advanced', 24.5, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Ty Dillon'), 'advanced', 26.1, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Shane Van Gisbergen'), 'advanced', 26.2, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Connor Zilisch'), 'advanced', 27.2, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Cole Custer'), 'advanced', 27.7, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Austin Hill'), 'advanced', 29.5, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Cody Ware'), 'advanced', 30.9, 'Bristol Chase History + Short-Track Form'),
  ((select id from races where chase_round = 3), (select id from drivers where name = 'Josh Bilicki'), 'advanced', 32.4, 'Bristol Chase History + Short-Track Form');

insert into feature_importances (race_id, model_type, feature, importance) values
  ((select id from races where chase_round = 3), 'basic', 'Succ%', 0.434),
  ((select id from races where chase_round = 3), 'basic', 'T10%', 0.397),
  ((select id from races where chase_round = 3), 'basic', 'ASP', 0.162),
  ((select id from races where chase_round = 3), 'basic', 'Fin%', 0.005),
  ((select id from races where chase_round = 3), 'basic', 'W%', 0.002),
  ((select id from races where chase_round = 3), 'advanced', 'wARP', 0.408),
  ((select id from races where chase_round = 3), 'advanced', 'Avg. PFAE', 0.349),
  ((select id from races where chase_round = 3), 'advanced', 'cPOMS', 0.111),
  ((select id from races where chase_round = 3), 'advanced', 'SS', 0.098),
  ((select id from races where chase_round = 3), 'advanced', 'PGAE', 0.033);
commit;
