-- Standalone: Kansas (race 4) predictions + feature importances.
-- Safe to re-run; replaces any existing Kansas rows.
begin;
update races set blend_note = '60% intermediate season form / 40% Kansas Chase history' where chase_round = 4;

delete from predictions where race_id = (select id from races where chase_round = 4);
delete from feature_importances where race_id = (select id from races where chase_round = 4);

insert into predictions (race_id, driver_id, model_type, projected_finish, data_source) values
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Denny Hamlin'), 'basic', 10.7, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Kyle Larson'), 'basic', 10.8, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Tyler Reddick'), 'basic', 11.2, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Christopher Bell'), 'basic', 12.5, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Chase Elliott'), 'basic', 13.3, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'William Byron'), 'basic', 13.4, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Ryan Blaney'), 'basic', 14.3, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Alex Bowman'), 'basic', 14.6, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Chris Buescher'), 'basic', 14.8, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Bubba Wallace'), 'basic', 15.6, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Joey Logano'), 'basic', 16.3, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Brad Keselowski'), 'basic', 16.6, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Ty Gibbs'), 'basic', 16.9, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Chase Briscoe'), 'basic', 17.6, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Austin Cindric'), 'basic', 18.0, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Carson Hocevar'), 'basic', 18.2, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Ryan Preece'), 'basic', 18.8, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Shane Van Gisbergen'), 'basic', 19.0, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Daniel Suarez'), 'basic', 20.0, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Austin Dillon'), 'basic', 20.3, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Ross Chastain'), 'basic', 20.3, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Zane Smith'), 'basic', 20.6, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Todd Gilliland'), 'basic', 20.7, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Erik Jones'), 'basic', 21.3, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Ricky Stenhouse Jr.'), 'basic', 22.3, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'John Hunter Nemechek'), 'basic', 22.9, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Riley Herbst'), 'basic', 22.9, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Michael McDowell'), 'basic', 23.3, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Noah Gragson'), 'basic', 23.8, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Josh Berry'), 'basic', 24.7, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'AJ Allmendinger'), 'basic', 25.0, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Cole Custer'), 'basic', 25.1, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Ty Dillon'), 'basic', 26.6, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Connor Zilisch'), 'basic', 27.0, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Austin Hill'), 'basic', 27.3, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Cody Ware'), 'basic', 27.3, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Denny Hamlin'), 'advanced', 10.4, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Kyle Larson'), 'advanced', 12.2, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Christopher Bell'), 'advanced', 12.5, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Tyler Reddick'), 'advanced', 12.7, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Chase Elliott'), 'advanced', 13.0, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Ryan Blaney'), 'advanced', 13.4, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'William Byron'), 'advanced', 13.7, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Alex Bowman'), 'advanced', 13.9, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Brad Keselowski'), 'advanced', 15.0, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Ty Gibbs'), 'advanced', 15.3, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Bubba Wallace'), 'advanced', 15.3, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Chase Briscoe'), 'advanced', 15.4, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Chris Buescher'), 'advanced', 15.5, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Carson Hocevar'), 'advanced', 15.7, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Ross Chastain'), 'advanced', 16.7, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Ryan Preece'), 'advanced', 17.2, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Joey Logano'), 'advanced', 17.4, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Austin Cindric'), 'advanced', 17.8, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Daniel Suarez'), 'advanced', 19.9, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Erik Jones'), 'advanced', 20.5, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Todd Gilliland'), 'advanced', 21.2, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Ricky Stenhouse Jr.'), 'advanced', 21.5, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Austin Dillon'), 'advanced', 21.5, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Josh Berry'), 'advanced', 21.7, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'John Hunter Nemechek'), 'advanced', 21.8, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Shane Van Gisbergen'), 'advanced', 22.0, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Zane Smith'), 'advanced', 23.0, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Riley Herbst'), 'advanced', 23.4, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Michael McDowell'), 'advanced', 23.8, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Noah Gragson'), 'advanced', 23.9, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Cole Custer'), 'advanced', 24.1, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Ty Dillon'), 'advanced', 24.2, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'AJ Allmendinger'), 'advanced', 25.6, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Connor Zilisch'), 'advanced', 25.8, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Cody Ware'), 'advanced', 27.2, 'Kansas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 4), (select id from drivers where name = 'Austin Hill'), 'advanced', 27.2, 'Kansas Chase History + Intermediate Form');

insert into feature_importances (race_id, model_type, feature, importance) values
  ((select id from races where chase_round = 4), 'basic', 'Succ%', 0.397),
  ((select id from races where chase_round = 4), 'basic', 'T10%', 0.365),
  ((select id from races where chase_round = 4), 'basic', 'ASP', 0.223),
  ((select id from races where chase_round = 4), 'basic', 'Fin%', 0.014),
  ((select id from races where chase_round = 4), 'basic', 'W%', 0.002),
  ((select id from races where chase_round = 4), 'advanced', 'wARP', 0.341),
  ((select id from races where chase_round = 4), 'advanced', 'Avg. PFAE', 0.271),
  ((select id from races where chase_round = 4), 'advanced', 'cPOMS', 0.246),
  ((select id from races where chase_round = 4), 'advanced', 'SS', 0.117),
  ((select id from races where chase_round = 4), 'advanced', 'PGAE', 0.025);
commit;
