-- Standalone: Las Vegas (race 5) predictions, feature importances, actual results + model scores.
-- Predictions were made after the race but from pre-race data only (season form through 10/3,
-- Vegas history 2022-25); results were added only after both models were logged.
-- Safe to re-run; replaces any existing Las Vegas rows.
begin;

update races set status = 'completed', winner = 'Chase Briscoe', blend_note = '60% intermediate season form (5 races + spring Vegas) / 40% Las Vegas history 2022-25' where chase_round = 5;

delete from predictions where race_id = (select id from races where chase_round = 5);
delete from feature_importances where race_id = (select id from races where chase_round = 5);
delete from results where race_id = (select id from races where chase_round = 5);
delete from model_scores where race_id = (select id from races where chase_round = 5);

insert into predictions (race_id, driver_id, model_type, projected_finish, data_source) values
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Denny Hamlin'), 'basic', 9.5, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'William Byron'), 'basic', 9.8, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Alex Bowman'), 'basic', 11.3, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Tyler Reddick'), 'basic', 11.5, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Kyle Larson'), 'basic', 11.8, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Chase Elliott'), 'basic', 12.0, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Ryan Blaney'), 'basic', 12.2, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Bubba Wallace'), 'basic', 12.3, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Daniel Suarez'), 'basic', 12.7, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Joey Logano'), 'basic', 12.8, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Christopher Bell'), 'basic', 12.9, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Ross Chastain'), 'basic', 13.2, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Brad Keselowski'), 'basic', 13.2, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Chris Buescher'), 'basic', 13.3, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Chase Briscoe'), 'basic', 17.0, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Ty Gibbs'), 'basic', 17.2, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Ryan Preece'), 'basic', 17.5, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Austin Cindric'), 'basic', 17.6, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Riley Herbst'), 'basic', 18.2, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Erik Jones'), 'basic', 18.6, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Carson Hocevar'), 'basic', 21.2, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Zane Smith'), 'basic', 21.2, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'AJ Allmendinger'), 'basic', 21.3, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'John Hunter Nemechek'), 'basic', 21.6, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Austin Dillon'), 'basic', 22.1, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Ricky Stenhouse Jr.'), 'basic', 23.5, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Shane Van Gisbergen'), 'basic', 24.3, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Michael McDowell'), 'basic', 25.8, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Todd Gilliland'), 'basic', 26.0, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Noah Gragson'), 'basic', 26.3, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Ty Dillon'), 'basic', 27.1, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Connor Zilisch'), 'basic', 27.4, 'Intermediate Form Only (no Las Vegas history)'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Josh Berry'), 'basic', 27.7, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Cole Custer'), 'basic', 28.1, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Austin Hill'), 'basic', 29.6, 'Intermediate Form Only (no Las Vegas history)'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Cody Ware'), 'basic', 29.6, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Denny Hamlin'), 'advanced', 9.2, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'William Byron'), 'advanced', 10.4, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Alex Bowman'), 'advanced', 11.2, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Tyler Reddick'), 'advanced', 12.1, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Kyle Larson'), 'advanced', 13.1, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Christopher Bell'), 'advanced', 13.2, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Daniel Suarez'), 'advanced', 13.8, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Ryan Blaney'), 'advanced', 14.5, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Brad Keselowski'), 'advanced', 14.7, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Bubba Wallace'), 'advanced', 15.1, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Chase Elliott'), 'advanced', 15.5, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Chase Briscoe'), 'advanced', 15.8, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Ty Gibbs'), 'advanced', 15.8, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Austin Cindric'), 'advanced', 16.0, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Joey Logano'), 'advanced', 16.0, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Chris Buescher'), 'advanced', 16.1, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Ross Chastain'), 'advanced', 16.3, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Erik Jones'), 'advanced', 17.9, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Ryan Preece'), 'advanced', 18.1, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Carson Hocevar'), 'advanced', 18.9, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'AJ Allmendinger'), 'advanced', 19.9, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Austin Dillon'), 'advanced', 22.2, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Riley Herbst'), 'advanced', 22.3, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Ricky Stenhouse Jr.'), 'advanced', 22.6, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'John Hunter Nemechek'), 'advanced', 22.6, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Zane Smith'), 'advanced', 24.2, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Noah Gragson'), 'advanced', 24.4, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Josh Berry'), 'advanced', 25.3, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Shane Van Gisbergen'), 'advanced', 25.5, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Michael McDowell'), 'advanced', 25.7, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Todd Gilliland'), 'advanced', 27.8, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Ty Dillon'), 'advanced', 28.3, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Cole Custer'), 'advanced', 28.6, 'Las Vegas Chase History + Intermediate Form'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Austin Hill'), 'advanced', 29.0, 'Intermediate Form Only (no Las Vegas history)'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Connor Zilisch'), 'advanced', 29.5, 'Intermediate Form Only (no Las Vegas history)'),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Cody Ware'), 'advanced', 32.2, 'Las Vegas Chase History + Intermediate Form');

insert into feature_importances (race_id, model_type, feature, importance) values
  ((select id from races where chase_round = 5), 'basic', 'Succ%', 0.571),
  ((select id from races where chase_round = 5), 'basic', 'T10%', 0.316),
  ((select id from races where chase_round = 5), 'basic', 'ASP', 0.11),
  ((select id from races where chase_round = 5), 'basic', 'Fin%', 0.002),
  ((select id from races where chase_round = 5), 'basic', 'W%', 0.001),
  ((select id from races where chase_round = 5), 'advanced', 'cPOMS', 0.425),
  ((select id from races where chase_round = 5), 'advanced', 'wARP', 0.386),
  ((select id from races where chase_round = 5), 'advanced', 'Avg. PFAE', 0.09),
  ((select id from races where chase_round = 5), 'advanced', 'SS', 0.054),
  ((select id from races where chase_round = 5), 'advanced', 'PGAE', 0.044);

insert into results (race_id, driver_id, start_pos, finish_pos, status, avg_running_position, fastest_laps, laps_led, pct_led, quality_passes, pct_top15) values
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Chase Briscoe'), 4, 1, 'Running', null, null, 175, 65.54, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Kyle Larson'), 6, 2, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Tyler Reddick'), 5, 3, 'Running', null, null, 1, 0.37, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Austin Cindric'), 7, 4, 'Running', null, null, 33, 12.36, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Ryan Blaney'), 20, 5, 'Running', null, null, 10, 3.75, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'William Byron'), 8, 6, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Chase Elliott'), 13, 7, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Bubba Wallace'), 9, 8, 'Running', null, null, 1, 0.37, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Shane Van Gisbergen'), 25, 9, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Joey Logano'), 23, 10, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Alex Bowman'), 15, 11, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Carson Hocevar'), 10, 12, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Chris Buescher'), 14, 13, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Daniel Suarez'), 11, 14, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'AJ Allmendinger'), 19, 15, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Denny Hamlin'), 1, 16, 'Running', null, null, 39, 14.61, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Ty Gibbs'), 2, 17, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Riley Herbst'), 22, 18, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Austin Dillon'), 28, 19, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Noah Gragson'), 36, 20, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Michael McDowell'), 18, 21, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Austin Hill'), 33, 22, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Christopher Bell'), 3, 23, 'Running', null, null, 8, 3.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Brad Keselowski'), 16, 24, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Erik Jones'), 21, 25, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Josh Berry'), 35, 26, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Cole Custer'), 24, 27, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Ryan Preece'), 12, 28, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'John Hunter Nemechek'), 32, 29, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Ross Chastain'), 17, 30, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Ty Dillon'), 29, 31, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Ricky Stenhouse Jr.'), 26, 32, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Todd Gilliland'), 27, 33, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Cody Ware'), 34, 34, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Connor Zilisch'), 31, 35, 'Running', null, null, 0, 0.0, null, null),
  ((select id from races where chase_round = 5), (select id from drivers where name = 'Zane Smith'), 30, 36, 'Running', null, null, 0, 0.0, null, null);

insert into model_scores (race_id, model_type, cv_mae, cv_r2, mae, rmse, r2, top5_hits, top10_hits, predicted_winner, predicted_winner_actual_finish) values
  ((select id from races where chase_round = 5), 'basic', 1.94, 0.89, 6.76, 8.17, 0.381, 2, 7, 'Denny Hamlin', 16),
  ((select id from races where chase_round = 5), 'advanced', 2.04, 0.9, 6.69, 7.85, 0.43, 2, 5, 'Denny Hamlin', 16);

select (select count(*) from predictions where race_id = (select id from races where chase_round = 5)) as predictions, (select count(*) from results where race_id = (select id from races where chase_round = 5)) as results;

commit;
